services:
  - type: web
    name: findreal-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: CLIENT_URL
        value: https://find-real-nops.vercel.app
      - key: MONGODB_URI
        value: "mongodb+srv://igfigma:figma@sjcet-website.aij6tqd.mongodb.net/findreal?retryWrites=true&w=majority&appName=SJCET-website"
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
