// Probabilistic Verdict Labels adhering to FindReal core guidelines
const VERDICT_LABELS = {
  VERIFIED_PROVENANCE: 'VERIFIED PROVENANCE',
  LIKELY_AUTHENTIC: 'LIKELY AUTHENTIC',
  INCONCLUSIVE: 'INCONCLUSIVE',
  SUSPICIOUS: 'SUSPICIOUS',
  HIGH_MANIPULATION_RISK: 'HIGH MANIPULATION RISK',
};

const MEDIA_TYPES = {
  IMAGE: 'image',
  AUDIO: 'audio',
  VIDEO: 'video',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

module.exports = {
  VERDICT_LABELS,
  MEDIA_TYPES,
  HTTP_STATUS,
};
